### ISSUE TITLE
Matplotlib Compatibility Issue 

### ISSUE THREAD

**Issue by MichealSBingham** [xIris-Corp/RoadAPI#2]
A while ago when I was working with it, I actually found a way to fix the TensorFlow issue but then I ran into the problem with matplotlib... I didn't know how to read the data exported from the model to draw the boundary boxes on the images. 

The code is supposed to handle this for us automatically, but the functions it uses is deprecated for current versions of matplotlib so you will either have to use an older version that it specifies (not sure which one) **or** figure out the format of how the model outputs the datapoints for the boundary boxes on the road defects and just rewrite the code to draw the boxes from scratch using whatever library you please (which may be the best way to go)

**Comment by ericsong01** [comment]
I was able to run the Detection code using matplotlib v3.1.3 and v3.3.3 (latest version) 
I updated to v3.3.3 using `conda install matplotlib=3.3.3`
